### ISSUE TITLE
[feature]: Als gebruiker wil ik een `softwareType` die past bij de aangeboden regelspecificaties en/of services

### ISSUE THREAD

**Issue by sgort** [OpenCatalogi/OpenCatalogiBundle#115]
### What is the goal of your request? Why should we do this?

zodat organisaties die regels toepassen deze

- kunnen vinden
- kunnen hergebruiken óf
- eigen regelspecificaties kunnen aanbieden om vindbaar én herbruikbaar te zijn

### The acceptance criteria of the feature

Beschrijving en toelichting is aanwezig in de `publiccode.yaml` documentatie

### Project Location

Documentatie pagina's

### Additional context

Zie voorbeeld IIT in dit issue: https://github.com/MinBZK/regels.overheid.nl/issues/321

**Comment by MWest2020** [comment]
Is inmiddels op OpenCatalogi
